### ISSUE TITLE
Kotlin-based implementation for multiplatform scenarios

### ISSUE THREAD

**Issue by vlsi** [bucket4j/bucket4j#283]
Hi, bucket4j looks great, however, it can't be used in Kotlin JS and Kotlin Native.

Have you considered implementing the core in Kotlin, so the library could be used with multiplatform projects as well?

See https://github.com/Kotlin/kotlinx.coroutines/issues/460

**Comment by vladimir-bukhtoyarov** [comment]
Hello Vladimir,

I think that integration with both Kotlin Native and Kotlin JS will be a big step forward for our library, that makes expansion to another languages more easy due to C/C++ compatibility, however current backlog tell me that we can not start working towards this direction prior spring 2023, and it is unpredictable how many time it will take.

So if you already have some pull-request to bring rate-limiting functionality to Kotlin-Courtliness then no reasons to wait more fundamental implementation from us.

**Comment by vladimir-bukhtoyarov** [comment]
Jetbrains has proven itself to be an unreliable supplier. Migration to the language that normally supported only by one proprietary IDE is not acceptable, because this support can left in one day.

**Comment by vlsi** [comment]
Technically speaking, IntelliJ IDEA Community supports Kotlin, and it is published under Apache License 2.0. So I would disagree with classifying it as "proprietary".
Here's Google's story: https://www.youtube.com/watch?v=o14wGByBRAQ&ab_channel=Devoxx

<img width="1904" alt="Screenshot from Google's Journey from Java to Kotlin for Server Side Programming by James Ward" src="https://github.com/bucket4j/bucket4j/assets/213894/74c356fd-a69d-4176-9b24-f7cc616fb7d4">

Sure your milage of "can left in one day" might differ from Google's.

**Comment by akuleshov7** [comment]
> Jetbrains has proven itself to be an unreliable supplier. Migration to the language that normally supported only by one proprietary IDE is not acceptable, because this support can left in one day.

By which IDE do you use now for Java?

**Comment by travispeloton** [comment]
bucket4j is a fairly complicated project, so although I haven't used Kotlin multiplatform for anything yet myself, it seems like a new GitHub project may be warranted. You would have to make some assumptions / trade-offs to get it started.
 
I've only used bucket4j with Redis via the [Lettuce](https://github.com/lettuce-io/lettuce-core) client, for example, but an offhand search for a Redis multiplatform client found results, but they are not actively maintained from what I saw.
