### ISSUE TITLE
Weird Consumption Behavior

### ISSUE THREAD

**Issue by lfaltran** [bucket4j/bucket4j#295]
Hello, I'm trying to use rate control inside an multi-threading context, but, there's something curious happening.

While using "bucket.asScheduler().tryConsume" some threads "get" tokens at same time, as soon new tokens are refilled, look bellow:

In this snapshot, I've 5 tokens refilled every 5 seconds, and started 4 threads requiring 3 tokens each. In that scenario, the first thread got the first 3 tokens, while the last ones has to wait no more be refilled, but, the second and third ones consume together.

`public static void main(String[] args) {
        Refill refill = Refill.intervally(5, Duration.ofSeconds(5));
        Bandwidth bandwidth = Bandwidth.classic(5, refill);

        SynchronizedBucket bucket = (SynchronizedBucket) Bucket4j.builder()
                .addLimit(bandwidth)
                .withSynchronizationStrategy(SynchronizationStrategy.SYNCHRONIZED)
                .build();

        ExecutorService executorService = Executors.newFixedThreadPool(4);

        int numTokensToConsume = 3;

        Runnable task = () -> {
            boolean consumed;

            System.out.println(new Date() + " [" + Thread.currentThread().getName() + "] Trying to consume tokens " + numTokensToConsume + " from bucket [" + Integer.toHexString(bucket.hashCode()) + "] with " + bucket.getAvailableTokens() + " available");

            try {
                consumed = bucket.asScheduler().tryConsume(numTokensToConsume, Duration.ofMinutes(30).toNanos(), BlockingStrategy.PARKING);
            } catch (InterruptedException e) {
                consumed = false;
            }

            if (consumed) {
                System.out.println(new Date() + " [" + Thread.currentThread().getName() + "] Consumed " + numTokensToConsume + "! " + bucket.getAvailableTokens() + " remaining");
            } else {
                System.out.println("No tokens available");
            }
        };

        System.out.println("Submitting the tasks for execution...");
        executorService.submit(task);
        executorService.submit(task);
        executorService.submit(task);
        executorService.submit(task);

        executorService.shutdown();
    }`

Execution output:

Submitting the tasks for execution...
Thu Aug 25 20:03:09 BRT 2022 [pool-1-thread-2] Trying to consume tokens 3 from bucket [37b707c9] with 5 available
Thu Aug 25 20:03:09 BRT 2022 [pool-1-thread-3] Trying to consume tokens 3 from bucket [37b707c9] with 5 available
Thu Aug 25 20:03:09 BRT 2022 [pool-1-thread-4] Trying to consume tokens 3 from bucket [37b707c9] with 5 available
Thu Aug 25 20:03:09 BRT 2022 [pool-1-thread-1] Trying to consume tokens 3 from bucket [37b707c9] with 5 available
Thu Aug 25 20:03:09 BRT 2022 [pool-1-thread-2] Consumed 3! -1 remaining
Thu Aug 25 20:03:14 BRT 2022 [pool-1-thread-3] Consumed 3! -2 remaining
Thu Aug 25 20:03:14 BRT 2022 [pool-1-thread-1] Consumed 3! -2 remaining
Thu Aug 25 20:03:19 BRT 2022 [pool-1-thread-4] Consumed 3! 3 remaining

Am I missing something, or doing it wrong? I've tried to use "Lock Free" strategy, but anything different happen. Although, the result of "bucket.getAvailableTokens" returns a negative value, that is pretty strange in my opnion.

Someone could help me what I'm doing wrong?

**Comment by lfaltran** [comment]
Hello again, after some research I think the "problem" is with behavior of method "asScheduler().tryConsume", doing a kind of "reservation" of "tokens", reflecting on least than zero on "available tokens". After that, a soon as fresh tokens are refilled, the thread is released and the execution continues.

If this thought is right, would be great to add some option to "lock" bandwidth lower limit to 0, to avoid some problems on throttling executions.

By now, I've just changed to "tryConsume" directly from "bucket", inside a "do while" (with some extra strategies to avoid infinite loop) and everything works as expected.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @lfaltran 

I am unable to compile your example because ```bucket.asScheduler().tryConsume``` returns ```CompletableFuture<Boolean>```.  Which version do you use?

**Comment by vladimir-bukhtoyarov** [comment]
Looks that you use somethin ```6.x``` version and bandwidth defined as ```Bandwidth bandwidth = Bandwidth.classic(5, Refill.intervally(5, Duration.ofSeconds(5)));```.

I do not see any strange behavior in output:
* When first thread comes bucket contains 5 tokens, thread consumes 3 tokens and reports 2 available tokens.
* When second thread comes it can not consume 3 tokens immediately, it needs to wait 5 seconds for next refill, because you provide 1800 seconds limit that is greater than 5, thread decrements available tokens by 3, and goes to sleep for 5 seconds, available tokens becomes -1 at this moment.
* When third thread comes it sees -1 available tokens so can not consume 3, also it calculates that after 5 seconds it will be 4 tokens(-1 + 5) so it decrements available tokens by 3 and goes to sleep for 5 seconds, available tokens becomes -4 at this moment.
* When fourth thread comes there is -4 available tokens, it calculates that after 5 seconds will be available 1 tokens(and it is not enough to consume), but after 10 seconds 6 tokens will be available(-4 + 5 *2), it decided that it can wait(since provide wait limit is huge), so it reduces available tokens by 3, and goes to sleep for 10 second, and available tokens becomes -7 at this moment.
* Second and third thread unparked after 5 seconds and see -2 available tokens, this number can be explained as 5(initial) - 3 - 3 - 3 - 3 + 5(refilled).
* Fourth thread unparked after 10 seconds and sees 2 available tokens, this number can be explained as 5(initial) - 3 - 3 - 3 - 3 + 5(refilled) + 5(refilled).

All numbers looks correct for me an can be easily explained. I strongly recommend to pay attention that you use internally refill and that is why second and third thread are unparked in same time, and since they unparked in same time, they both see the same number of available tokens.

**Comment by lfaltran** [comment]
Hello @vladimir-bukhtoyarov sorry for lack basic information about my environment.

I'm on 6.0.1 as inheritance of working with Spring Boot 2.1.5 on JDK 8

With your explanation I understood the behavior of token availability and how "tryConsume" works. During my tests I've tried to use "greedy" for refill strategy, but on my scenario the results not works as expected.

I'm trying to consume an External API, that has throttling of 50 requests by minute, thats way, under no circumstances can I exceed this limit, so, what is the best Refill strategy to work? and how to configure the bandwidth of my bucket?

**Comment by vladimir-bukhtoyarov** [comment]
Token bucket algorithm is not defined in terms of consumption rate, it can be described in three numbers:
* *max_size* aka capacity - maximum amount of tokens that bucket can hold.
* *current_size* - amount of tokens that currently available to be consumed.
* *refill_rate* - the speed in which consumed tokens are added back to bucket.

So, there is no place to something like consumption rate in the math model of token bucket algorithm, and limit ```N tokens/ M window``` can not be formulated, because consumption rate does not the same that refill rate. 

Although strong limit can not be formulated directly, there are alternative way to formulate limit 50 requests by minute:
```
Bandwidth.classic(40, Refill.greedy(10, Duration.ofMinute(1)));

// or 
Bandwidth.classic(30, Refill.greedy(20, Duration.ofMinute(1)));

// or 
Bandwidth.classic(10, Refill.greedy(40, Duration.ofMinute(1)));

// or 
Bandwidth.classic(10, Refill.greedy(35, Duration.ofMinute(15)));

// or 
Bandwidth.classic(25, Refill.greedy(25, Duration.ofMinute(1)));
```
With all configurations above the strong limit is satisfied. Try to choose one of them based on supposed average rate.
