### ISSUE TITLE
Adding a separate blocking time.

### ISSUE THREAD

**Issue by sreyasvpariyath** [bucket4j/bucket4j#311]
Hi I have been trying to ratelimit my spring boot api (Login Api) using bucket4j. I am trying to black list an IP for an hour if I get too many unsuccessful request in a Minute. Basically I want to block the client's ip address for an hour if I get 20 unsuccessful request in 1 Minute. 
Currently I am trying to create 1 bucket/ ip and trying to do everything manually. Is there a simple configuration where I could set the blocking time.? 
Thanks

**Comment by vladimir-bukhtoyarov** [comment]
Hello @sreyasvpariyath 

I recomend to try [bucket4j-spring-boot-starter](https://github.com/MarcGiffing/bucket4j-spring-boot-starter), it is very powerful integration with SpringBoot.

**Comment by vladimir-bukhtoyarov** [comment]
Blocking a bucket for specific time is not a rate-limiting responsibility, because it is kind of throttling. 
There is issue in backlog https://github.com/bucket4j/bucket4j/issues/78 that is addressed to introduce throttling concepts to the library, but it will not be implemented in the 2022. So you should to maintain blacklisting manually until implementation of #78
