### ISSUE TITLE
Redis Cluster Support for LettuceBasedProxyManager

### ISSUE THREAD

**Issue by vinaypareek** [bucket4j/bucket4j#376]
As per [documentation](https://appdoc.app/artifact/com.bucket4j/bucket4j-redis/8.0.1/io.github.bucket4j.redis/io/github/bucket4j/redis/lettuce/cas/LettuceBasedProxyManager.html) looks current LettuceBasedProxyManager implementation support only the standalone Redis ( its accept the RedisClient as param not the RedisClusterClient). Wanted to confirmed does my understanding is correct, if yes, then is there any timeline/plan for support the RedisCluster for LettuceBasedProxyManager.
Or anyother workaround to support redis cluster with LettuceBasedProxyManager.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @vinaypareek 

bucket4j-redis supports RedisCluster for Letucci since 8.2.0 https://bucket4j.com/8.2.0/release-notes.html
Your link points to obsolete version, there is more fresh https://appdoc.app/artifact/com.bucket4j/bucket4j-redis/8.3.0/io.github.bucket4j.redis/io/github/bucket4j/redis/lettuce/cas/LettuceBasedProxyManager.html

**Comment by vinaypareek** [comment]
Thanks @vladimir-bukhtoyarov , just noticed that it was release with 8.2.0 version. https://github.com/bucket4j/bucket4j/pull/338 About to close the issue. Thanks a lot again.
