### ISSUE TITLE
Synchronization of `Bucket` with the distributed setup

### ISSUE THREAD

**Issue by KaeYan93** [bucket4j/bucket4j#402]
Hi, 

When using bucket4j with Hazelcast like the code below, for the `Bucket` instance, do i need to do some synchronization when multiple thread might be using the `Bucket` instance? For your info, I storing this bucket in `HashMap` and I am running my apps in the cluster setup. 

```
IMap<K, byte[]> map = ...;
private static final HazelcastProxyManager<K> proxyManager = new HazelcastProxyManager(map);

...
BucketConfiguration configuration = BucketConfiguration.builder()
    .addLimit(Bandwidth.simple(1_000, Duration.ofMinutes(1)))
    .build();

Bucket bucket = proxyManager.builder().build(key, configuration);

```

**Comment by vladimir-bukhtoyarov** [comment]
Hello @KaeYan93 

> do i need to do some synchronization when multiple thread might be using the Bucket instance?

No, library solves concurrency problems by itself, based on low-level primitives provided by underlying backend. Specifically for Hazelcast it is EntryProcessors. For another backends, it might be another concurrency primitives like explicit locking, CAS or data level locking.

> For your info, I storing this bucket in HashMap

Usually, It is also not nessesarry to store buckets somewhere, you can just build bucket, interact with bucket and forget about bucket, because BucketProxy is cheap and does not hold anything more than primary key. Of coarse it is nothing wrong to store buckets in hashmap, util hashmap size is small and can be a cause of OOM.
