### ISSUE TITLE
remove all buckets

### ISSUE THREAD

**Issue by elahehhabibi** [bucket4j/bucket4j#437]
I Use Redis and Redisson for distribution support. 
I want the new configuration(capacity, interval, ExpirationAfterWriteStrategy,...) to take effect on the existing buckets on redis cache after restarting the application, but in my test if a specific bucket already exists in redis, the new configuration are not applied(because defualt ExpirationAfterWriteStrategy is none and  existing buckets are not delete ). Is there a way to delete all buckets present in Redis(i cann't use replaceConfiguration because i don't know bucket keys)?

**Comment by vladimir-bukhtoyarov** [comment]
> i cann't use replaceConfiguration because i don't know bucket keys

[Implicit-configuration-replacement](https://bucket4j.com/8.7.0/toc.html#implicit-configuration-replacement) is designed for such case.

**Comment by elahehhabibi** [comment]
Thankyou for your response
Is way to get version of current configuration?

**Comment by vladimir-bukhtoyarov** [comment]
> in order to keep track of versions i have to keep version of current instance in separate cache in order to get it on server startup and increment it to newer version. in case of multi instance servers this might be an issue because all servers will get this cache and increment it.

You can store the version in application configuration. It is obviously that in case of upgrade different instances of your application will have different version until whole cluster will be upgraded, but it is not problem, the design of implicit configuration replacement covers such case - configuration is being replaced when it detected that persisted version is less than configured version, but configuration is not being replaced when persisted version is greater than configured, so having different nodes with different versions is not problem, it is covered by design. Just start to count version from 1 in new deployment and all active buckets will be reconfigured after upgrade. Of course, buckets that will not be used after upgrade will not be reconfigured.


>  so is there any way to get cache name created for the proxy and remove all elements in cache on startup.

No, there is no such functionality.
