### ISSUE TITLE
Add an online javadoc

### ISSUE THREAD

**Issue by freya022** [bucket4j/bucket4j#488]
As part of my online documentation, I'd like if the javadocs were hosted, so I can link to them.

The only alternative i know is by using javadoc.io, which have been proven unreliable these days, so I'd like to stay away from it as it makes builds fail when it is down.

Would be nice if you either provided them on your website, or at least on GitHub Pages

**Comment by vladimir-bukhtoyarov** [comment]
Hello @freya022 

I will think about it.

**Comment by vladimir-bukhtoyarov** [comment]
What is wrong with javadoc.io?  I see that all works https://javadoc.io/doc/com.bucket4j/bucket4j_jdk17-core/latest/io.github.bucket4j.core/module-summary.html

**Comment by freya022** [comment]
It does currently work, I was talking about it being down multiple times in the last months, causing issues when it is down

**Comment by freya022** [comment]
You can have online javadocs by setting up the CI to deploy the documentation on GitHub Pages, you can even set your domain to point to them, for free

**Comment by vladimir-bukhtoyarov** [comment]
![image](https://github.com/user-attachments/assets/f35224c4-3426-48fc-bdb0-73571cb2a33c)
Since, I leave in Russia, I have no way to pay for advanced space to Microsoft, so I prefer to utilize available space to store references that is accesable by bucket4j.com. 

I will return to this problem when 1GB will be utilized references, at this point I will acquire hosting at global south payment zone. Currently I do not want to do something, in face when javadocs.io works mostly time.
