### ISSUE TITLE
How to build buckets that refill monthly at the first day of the month?

### ISSUE THREAD

**Issue by PalatinatePotatoFarmer** [bucket4j/bucket4j#506]
Hi all,

we are building a rate limiting solution for some features in our application that tries to cover two aspects: 

- fairness across different users, for which users get (small) buckets that refill on the order of minutes), but also 
- having a "monthly allowance" for users that refills, e.g., at the first second of the new month.

That way, users cannot become "noisy neighbours" by excessive use in a small time frame and we can limit their overall use of the feature to prevent us losing money in case of overly heavy usage. 
(If by now you guessed that this is about the use of LLMs within our features, you guessed correctly ;-))

The first approach is straightforward and appears to be exactly what bucket4j is meant for.
The second problem seems easy at first ("just use refillIntervallyAligned(...)"), but this does not work due to the different length of months (Just using a constant refill interval of 30 days is not considered acceptable.).
Alas, it seems not to be intended to have custom refill strategy implementations - or am I overlooking something here?

One crude workaround could be to use a scheduler (Quartz etc.) to refill the "monthly allowance" bucket "externally" (and set the "regular" refill behavior just to refill with 0). But that would require additional effort that ensures refills happen even if the rate limiter service is down when the refill is scheduled. 
Another option could be to use the time of last refill (which buckets hold internally anyway, in the BucketState) and whenever checking against/consuming from such a bucket, first check if the last refill was in a previous month, and if it was, trigger a refill "on demand"/"on access" by then calling reset(). Alas, the bucket does not seem to give callers access to the last refill timestamp it manages internally, so we would have to manage that ourselves. And there we are near to the point where we start building our own bucket implementation...

I am assuming that there is a better way to achieve this with bucket4j. One answer could also be to not even try using bucket4j for that, so that we know we should look for other solutions for the second aspect, but obviously we would prefer to use one tool for both aspects.

Any suggestions welcome.

Regards

J

**Comment by vladimir-bukhtoyarov** [comment]
Hello @PalatinatePotatoFarmer 

I strongly reccomend to avoid of mixing rate-limiting and billing code together. You hope that reusuing Bucket4j in billing domain, will allow to save some time for programming, but you will pay for this decision twice after changes in requirement. Requirements for rate-limiting usually can be threated as stable, you just choose algorithm like(token-bucket), and after you usually change only concrete parameters like capacity or refill, but you never change algorithm, because all rete-limiting algorithms are close to each other at high-level, you can not achive something meaningfull when replace token-bucket to sliding-window. 

While requirements for billing rules/plans are being changed frequently, in order to provide unique offer for particular group of client. If today your billing policy is simple, it does not mean that tommorrow the product owner will not decay to do it more complex.

So, exersizes for hacking with Bucket4j for mounthly refill are useless. Just use Bucket4j for short-term rate-limiting, and serve mounthly(tomorrow it can weekly) limits separatelly.

**Comment by PalatinatePotatoFarmer** [comment]
THX for the feedback @vladimir-bukhtoyarov 
I fully agree with your assessment about the often changing billing model. ;-)
We also planned to split the two aspects into different microservices (one close to the SaaS deployment (of which there are many), one "in front of" all LLMs of one world region), but would have liked to use the same technology for both if possible.
Still, bucket4j gets surprising close to what we would need - the only missing thing being a "refill strategy" that does not only support fixed time intervals between refills (1h, 1d, ...) but strategies like "every Wednesday night at 22:00" (and that could even be accomplished with bucket4j by setting first refill time to a Wednesday, using "intervallyAligned" and specifying 7 days refill interval) or "every nth day of the month at time t" or even fancier "first Sunday of the month". 
Maybe having more flexible custom refill strategies would be something to consider for a future version? 
I have not looked into the details of the bucket implementation, but when just storing last refill time and current token amount, one could even modify the refill strategy on an existing bucket (i.e., without losing the current token amount).
Anyway, we will have to come up with a custom implementation that does something along that lines.

**Comment by vladimir-bukhtoyarov** [comment]
> Maybe having more flexible custom refill strategies would be something to consider for a future version?

No, it is not planned because:
* Firstly to explicitly prevent to use rate-limiter as billing abstraction.
* Secondly, it will require significant efforts to support this feature for distributed Buckets, when custom refill strategy must be serialized over network(like in Hazelcast or Infinispan), especially it will be hard to serialize behavior from java into javascript in case of Redis stored procedures.
* There are some API that makes proposal when tokens can be consumed(like [bucket.asBlocking().tryConsume(...)](https://github.com/bucket4j/bucket4j/blob/8.13/bucket4j-core/src/main/java/io/github/bucket4j/BlockingBucket.java#L62)), custom refill strategy will make thess API's slow. 

So only one way to achive what you needs - creating own fork, it is obviously that you need only small subset of library functionality, so maybe all problems described above will not take effects to subset of functionality that you need.
